// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtohkmdolbyfubdzhjiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0b2hrbWRvbGJ5ZnViZHpoaml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTcxNzcsImV4cCI6MjA3MDA3MzE3N30.TNm8KpUy5PqPeh6BRC0LJOR5722sxSsuaBn1U3B-GNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});